"""
=============================================================
  VetDesk AI — REST API Layer  (Phase 5)
  api.py
=============================================================
  Wraps the Phase 3 agent in a FastAPI REST API so that
  any external software can talk to VetDesk AI over HTTP.

  PHASE 4 vs PHASE 5 — the difference:
    Phase 4 (Streamlit) = a browser app. Humans use it.
    Phase 5 (FastAPI)   = a service. Other SOFTWARE uses it.

    Things that can now connect:
      - A clinic's PIMS (patient management system)
      - A WhatsApp bot via Twilio webhook
      - A mobile app
      - A hospital receptionist dashboard
      - An automated intake form on a clinic website

  ENDPOINTS:
    GET  /health        → check API is alive
    POST /chat          → full agent reply + triage level
    POST /triage        → triage classification only (faster)
    DELETE /session/:id → clear a session

  INTERACTIVE DOCS (auto-generated by FastAPI):
    http://localhost:8000/docs   ← test every endpoint in browser

  TO RUN:
    pip install fastapi uvicorn scikit-learn
    uvicorn api:app --reload --port 8000

  EXAMPLE CURL CALL:
    curl -X POST http://localhost:8000/chat \
         -H "Content-Type: application/json" \
         -d '{"message": "my dog ate chocolate", "session_id": "user-001"}'

  EXAMPLE RESPONSE:
    {
      "session_id":     "user-001",
      "reply":          "This sounds like an emergency...",
      "triage_level":   "EMERGENCY",
      "booking_active": false,
      "timestamp":      "2025-04-11T10:00:00"
    }
=============================================================
"""

import uuid
from datetime import datetime
from typing import Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from vet_agent import VetAgent
from vet_classifier import classify as triage_classify
from vet_sop_knowledge import CLINIC_NAME, CLINIC_PHONE, EMERGENCY_LINE


# ─────────────────────────────────────────────────────────────
#  APP
# ─────────────────────────────────────────────────────────────

app = FastAPI(
    title="VetDesk AI API",
    description=(
        f"REST API for the VetDesk AI veterinary receptionist agent.\n\n"
        f"Handles triage classification, SOP-based Q&A, and appointment booking.\n\n"
        f"Emergency line: **{EMERGENCY_LINE}**"
    ),
    version="1.0.0",
)

# Allow any frontend or external service to call this API.
# In production: replace "*" with your allowed domains.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ─────────────────────────────────────────────────────────────
#  SESSION STORE
#  Each caller gets a session_id so multi-turn booking works.
#  In production: use Redis or a database instead of a dict.
# ─────────────────────────────────────────────────────────────

SESSIONS: dict[str, VetAgent] = {}


def get_or_create_session(session_id: Optional[str]) -> tuple[str, VetAgent]:
    """Return an existing agent session or create a new one."""
    sid = session_id or str(uuid.uuid4())
    if sid not in SESSIONS:
        SESSIONS[sid] = VetAgent()
    return sid, SESSIONS[sid]


# ─────────────────────────────────────────────────────────────
#  REQUEST / RESPONSE MODELS
#  Pydantic models define what the API accepts and returns.
#  FastAPI generates /docs automatically from these.
# ─────────────────────────────────────────────────────────────

class ChatRequest(BaseModel):
    message: str
    session_id: Optional[str] = None


class ChatResponse(BaseModel):
    session_id: str
    reply: str
    triage_level: str       # EMERGENCY / MODERATE / ROUTINE / UNKNOWN
    booking_active: bool    # True if the agent is mid-booking-flow
    timestamp: str


class TriageRequest(BaseModel):
    message: str


class TriageResponse(BaseModel):
    message: str
    triage_level: str       # EMERGENCY / MODERATE / ROUTINE / UNKNOWN
    method: str             # keyword / pattern / contextual / none
    normalised: str         # cleaned version of input (useful for debugging)
    timestamp: str


# ─────────────────────────────────────────────────────────────
#  ENDPOINTS
# ─────────────────────────────────────────────────────────────

@app.get("/health", tags=["System"])
def health_check():
    """
    Check that the API is running.

    Use this for uptime monitoring or to verify your connection
    before sending patient messages.
    """
    return {
        "status":          "ok",
        "clinic":          CLINIC_NAME,
        "emergency_line":  EMERGENCY_LINE,
        "sessions_active": len(SESSIONS),
        "timestamp":       datetime.utcnow().isoformat(),
    }


@app.post("/chat", response_model=ChatResponse, tags=["Chat"])
def chat(request: ChatRequest):
    """
    Main endpoint — send a message, get a full agent reply.

    This is the endpoint your clinic software, WhatsApp bot,
    or mobile app should call for every owner message.

    **session_id** ties messages together so multi-turn
    booking flows work correctly. Generate one UUID per user
    session and reuse it throughout that conversation.

    If you omit session_id, the API creates one and returns it —
    save it from the first response and send it back each time.
    """
    if not request.message.strip():
        raise HTTPException(status_code=400, detail="Message cannot be empty.")

    session_id, agent = get_or_create_session(request.session_id)

    triage = triage_classify(request.message)
    reply  = agent.respond(request.message)

    return ChatResponse(
        session_id=session_id,
        reply=reply,
        triage_level=triage["classification"],
        booking_active=agent.booking.active,
        timestamp=datetime.utcnow().isoformat(),
    )


@app.post("/triage", response_model=TriageResponse, tags=["Triage"])
def triage_only(request: TriageRequest):
    """
    Triage classification only — no RAG, no booking logic.

    Use this when you only need the severity level, not a full reply.
    It is faster and cheaper to call than /chat.

    **Useful for:**
    - Auto-flagging urgent messages in a clinic dashboard
    - Routing incoming calls to on-call staff
    - Filtering a message queue by severity before human review
    """
    if not request.message.strip():
        raise HTTPException(status_code=400, detail="Message cannot be empty.")

    result = triage_classify(request.message)

    return TriageResponse(
        message=request.message,
        triage_level=result["classification"],
        method=result["method"],
        normalised=result["normalised"],
        timestamp=datetime.utcnow().isoformat(),
    )


@app.delete("/session/{session_id}", tags=["System"])
def clear_session(session_id: str):
    """
    Clear a session and its booking state.

    Call this when a conversation ends to free memory.
    In a production system this would be handled automatically
    by a session TTL in Redis.
    """
    if session_id not in SESSIONS:
        raise HTTPException(status_code=404, detail="Session not found.")
    del SESSIONS[session_id]
    return {
        "status":     "cleared",
        "session_id": session_id,
        "timestamp":  datetime.utcnow().isoformat(),
    }


# ─────────────────────────────────────────────────────────────
#  INTEGRATION GUIDE (printed on startup in test mode)
# ─────────────────────────────────────────────────────────────

INTEGRATION_GUIDE = """
╔══════════════════════════════════════════════════════════════╗
║           VetDesk AI — Integration Reference                 ║
╠══════════════════════════════════════════════════════════════╣
║                                                              ║
║  Base URL (local):  http://localhost:8000                    ║
║  Interactive docs:  http://localhost:8000/docs               ║
║                                                              ║
║  ENDPOINTS                                                   ║
║  GET  /health               → uptime check                   ║
║  POST /chat                 → full reply + triage            ║
║  POST /triage               → triage level only              ║
║  DELETE /session/{id}       → clear session                  ║
║                                                              ║
║  CHAT REQUEST BODY                                           ║
║  {                                                           ║
║    "message":    "my dog ate chocolate",    ← required       ║
║    "session_id": "user-abc-123"             ← optional       ║
║  }                                                           ║
║                                                              ║
║  CHAT RESPONSE                                               ║
║  {                                                           ║
║    "session_id":     "user-abc-123",                         ║
║    "reply":          "This sounds like an emergency...",     ║
║    "triage_level":   "EMERGENCY",                            ║
║    "booking_active": false,                                  ║
║    "timestamp":      "2025-04-11T10:00:00"                   ║
║  }                                                           ║
║                                                              ║
║  TRIAGE LEVELS                                               ║
║  EMERGENCY → call emergency line immediately                 ║
║  MODERATE  → vet needed same or next day                     ║
║  ROUTINE   → normal appointment                              ║
║  UNKNOWN   → could not classify                              ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
"""


# ─────────────────────────────────────────────────────────────
#  TEST SUITE — runs without starting the HTTP server
# ─────────────────────────────────────────────────────────────

def run_api_tests():
    """Tests the API logic directly (no HTTP server needed)."""

    print(f"\n{'=' * 62}")
    print("  VetDesk AI — Phase 5 API Test Suite")
    print(f"{'=' * 62}")

    agent = VetAgent()
    passed = failed = 0
    failures = []

    test_cases = [
        # (message, expected_fragment_in_reply, expected_triage)
        ("my dog ate chocolate",               "emergency",   "EMERGENCY"),
        ("my cat cant breathe",                "emergency",   "EMERGENCY"),
        ("what are your hours",                "Monday",      "ROUTINE"),
        ("are you open on sundays",            "closed",      "ROUTINE"),
        ("how much is a rabies vaccine",       "15",          "ROUTINE"),
        ("how much does it cost to spay",      "200",         "ROUTINE"),
        ("do you treat rabbits",               "rabbit",      "ROUTINE"),
        ("what services do you offer",         "Consultation","UNKNOWN"),
        ("my rabbit hasnt eaten today",        "today",       "MODERATE"),
        ("my dog has been vomiting 3 times",   "vet",         "MODERATE"),
        ("book an appointment",                "book",        "ROUTINE"),
        ("should i fast my rabbit before surgery", "NOT",     "UNKNOWN"),
    ]

    for message, expected_fragment, expected_triage in test_cases:
        triage = triage_classify(message)
        reply  = agent.respond(message)
        agent.booking.reset()

        reply_ok  = expected_fragment.lower() in reply.lower()
        triage_ok = triage["classification"] == expected_triage
        ok = reply_ok and triage_ok

        tri_color = "\033[91m" if triage["classification"] == "EMERGENCY" else \
                    "\033[93m" if triage["classification"] == "MODERATE"  else \
                    "\033[92m"
        sym = "\033[92m✓\033[0m" if ok else "\033[91m✗\033[0m"

        print(
            f"  {sym}  "
            f"{tri_color}[{triage['classification']:9}]\033[0m  "
            f"{message[:48]}"
        )

        if ok:
            passed += 1
        else:
            failed += 1
            tag = "" if reply_ok else f" [reply missing '{expected_fragment}']"
            tag += "" if triage_ok else f" [triage: got {triage['classification']}, expected {expected_triage}]"
            failures.append((message, tag, reply[:90]))

    print(f"\n  Results: {passed}/{len(test_cases)} passed")
    if failures:
        print("\n  Failed cases:")
        for msg, tag, got in failures:
            print(f"    {tag}")
            print(f"    Query: '{msg}'")
            print(f"    Reply: '{got}...'")

    print(f"{'=' * 62}")
    print(INTEGRATION_GUIDE)

    return passed, failed


# ─────────────────────────────────────────────────────────────
#  ENTRY POINT
# ─────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1 and sys.argv[1] == "test":
        run_api_tests()
    else:
        run_api_tests()
        print("Starting API server on http://localhost:8000 ...")
        print("Interactive docs: http://localhost:8000/docs\n")
        import uvicorn
        uvicorn.run("api:app", host="0.0.0.0", port=8000, reload=True)
